### ISSUE TITLE
check if the http prefix is part of the url

### ISSUE THREAD

**Issue by igorgaelzer** [spiermar/yakinaround.com#8]
Não sei se é feature, mas nos blog posts ao colocar a URL ele já adiciona a URL do nosso site antes do link. Coloquei a URL da Nordweg pra testar e aí o link vai pra http://tracker.yakinaround.com/www.nordweg.com.

Acho legal deixar aberto que aí é mais flexível. Vai que saímos nas notícias de um blog/jornal local ou tem outros links que queremos colocar em determinado lugar.

**Comment by spiermar** [comment]
Não é isto. O link está correto, mas quando não se tem http:// na frente, o navegador assume que é um link para o mesmo site. O mesmo vai acontecer para qualquer link que tu vai criar em qualquer pagina. Posso adicionar um filtro que verifica a Url e faz o append conforme necessário.

**Comment by spiermar** [comment]
Fixed. b75e238fc1d744ef89f76c010f2e5858e3943343

**Comment by igorgaelzer** [comment]
Entendi! De qualquer forma, melhor assim ;)
