### ISSUE TITLE
parse video link and create right embed code

### ISSUE THREAD

**Issue by igorgaelzer** [spiermar/yakinaround.com#9]
It took me a while to figure out why the video preview wasn't showing up. Tried regular Youtube link, then the iFrame, then I though maybe it's supposed to be Vimeo, and finally I realized it could be the URL inside the iFrame and it worked.

Suggestion: Add a little help text saying something like...

On Youtube, click Share > Embed and paste the URL inside the iFrame tag below.

The other solution (more user friendly, but not that relevant to us) would be to just allow pasting the URL shown in the browser.

**Comment by spiermar** [comment]
I can parse the link and figure our which embed code to use.

**Comment by spiermar** [comment]
http://stackoverflow.com/questions/5612602/improving-regex-for-parsing-youtube-vimeo-urls

**Comment by spiermar** [comment]
Fixed on https://github.com/spiermar/yakin-tracker/commit/f554f51e820cd02b9b7c16ac010c2aad4cbc97c7

**Comment by igorgaelzer** [comment]
Even better. O user joga qualquer coisa e funciona mesmo assim.
